
CONSTANTS = {
    'SEP': '[SEP]',
    'CLS': '[CLS]',
    'UNK': '[UNK]',
    'PAD': '[PAD]',
    'TOK_MAP_PAD': -100,
    'WORDPIECE': 'X'
}


DEID_TYPES = [
    '[PAD]',
    '[UNK]',
    '[CLS]',
    '[SEP]',
    'E-AGE',
    'S-ORGANIZATION',
    'I-AGE',
    'E-PATIENT',
    'O',
    'I-STATE',
    'S-PATIENT',
    'E-DEVICE',
    'B-AGE',
    'I-PATIENT',
    'E-PHONE',
    'E-HEALTHPLAN',
    'I-STREET',
    'I-ZIP',
    'B-STATE',
    'B-MEDICALRECORD',
    'S-LOCATION-OTHER',
    'E-COUNTRY',
    'S-MEDICALRECORD',
    'B-DOCTOR',
    'E-PROFESSION',
    'B-HOSPITAL',
    'B-LOCATION-OTHER',
    'E-DOCTOR',
    'I-FAX',
    'S-DOCTOR',
    'B-PATIENT',
    'E-MEDICALRECORD',
    'I-DATE',
    'S-CITY',
    'B-EMAIL',
    'I-LOCATION-OTHER',
    'B-HEALTHPLAN',
    'S-COUNTRY',
    'B-CITY',
    'I-IDNUM',
    'E-URL',
    'E-FAX',
    'I-MEDICALRECORD',
    'I-URL',
    'B-URL',
    'S-DEVICE',
    'B-STREET',
    'E-HOSPITAL',
    'I-DOCTOR',
    'I-CITY',
    'E-LOCATION-OTHER',
    'I-PROFESSION',
    'S-HOSPITAL',
    'E-CITY',
    'S-PROFESSION',
    'I-PHONE',
    'S-AGE',
    'B-DATE',
    'S-STREET',
    'B-IDNUM',
    'S-USERNAME',
    'S-BIOID',
    'B-PHONE',
    'E-DATE',
    'I-HOSPITAL',
    'S-IDNUM',
    'B-ORGANIZATION',
    'S-ZIP',
    'I-EMAIL',
    'E-STATE',
    'B-ZIP',
    'E-STREET',
    'I-ORGANIZATION',
    'E-IDNUM',
    'B-DEVICE',
    'E-ZIP',
    'S-DATE',
    'E-ORGANIZATION',
    'S-PHONE',
    'S-STATE',
    'B-PROFESSION',
    'I-COUNTRY',
    'B-COUNTRY',
    'E-EMAIL',
    'I-DEVICE',
    'B-FAX'
]
DEID_LABELS = dict()
for i, entity in enumerate(DEID_TYPES):
    DEID_LABELS['entity'] = i


COHORT_LABEL_CONSTANTS = {
    'U': 0,
    'Q': 1,
    'N': 2,
    'Y': 3,
}

COHORT_DISEASE_LIST = [
    'Obesity',
    'Diabetes',
    'Hypercholesterolemia',
    'Hypertriglyceridemia',
    'Hypertension',
    'CAD',
    'CHF',
    'PVD',
    'Venous Insufficiency',
    'OA',
    'OSA',
    'Asthma',
    'GERD',
    'Gallstones',
    'Depression',
    'Gout'
]


COHORT_DISEASE_CONSTANTS = {
    'Obesity': 0,
    'Diabetes': 1,
    'Hypercholesterolemia': 2,
    'Hypertriglyceridemia': 3,
    'Hypertension': 4,
    'CAD': 5, 
    'CHF': 6,
    'PVD': 7,
    'Venous Insufficiency': 8,
    'OA': 9,
    'OSA': 10,
    'Asthma': 11,
    'GERD': 12,
    'Gallstones': 13,
    'Depression': 14,
    'Gout': 15
}

MAX_COHORT_NUM_SENTS = 256 # number of sentences in chart
