OUTSIDE = 'O'
SEP = '[SEP]'
CLS = '[CLS]'
UNK = '[UNK]'
PAD = '[PAD]'
WORDPIECE = 'X'
BERT_MAX_SENT_LEN = 512

DEID_TYPES = [
    PAD,
    'E-AGE',
    'S-ORGANIZATION',
    'I-AGE',
    'E-PATIENT',
    'O',
    'I-STATE',
    'S-PATIENT',
    'E-DEVICE',
    'B-AGE',
    'I-PATIENT',
    'E-PHONE',
    'E-HEALTHPLAN',
    'I-STREET',
    'I-ZIP',
    'B-STATE',
    'B-MEDICALRECORD',
    'S-LOCATION-OTHER',
    'E-COUNTRY',
    'S-MEDICALRECORD',
    'B-DOCTOR',
    'E-PROFESSION',
    'B-HOSPITAL',
    'B-LOCATION-OTHER',
    'E-DOCTOR',
    'I-FAX',
    'S-DOCTOR',
    'B-PATIENT',
    'E-MEDICALRECORD',
    'I-DATE',
    'S-CITY',
    'B-EMAIL',
    'I-LOCATION-OTHER',
    'B-HEALTHPLAN',
    'S-COUNTRY',
    'B-CITY',
    'I-IDNUM',
    'E-URL',
    'E-FAX',
    'I-MEDICALRECORD',
    'I-URL',
    'B-URL',
    'S-DEVICE',
    'B-STREET',
    'E-HOSPITAL',
    'I-DOCTOR',
    'I-CITY',
    'E-LOCATION-OTHER',
    'I-PROFESSION',
    'S-HOSPITAL',
    'E-CITY',
    'S-PROFESSION',
    'I-PHONE',
    'S-AGE',
    'B-DATE',
    'S-STREET',
    'B-IDNUM',
    'S-USERNAME',
    'S-BIOID',
    'B-PHONE',
    'E-DATE',
    'I-HOSPITAL',
    'S-IDNUM',
    'B-ORGANIZATION',
    'S-ZIP',
    'I-EMAIL',
    'E-STATE',
    'B-ZIP',
    'E-STREET',
    'I-ORGANIZATION',
    'E-IDNUM',
    'B-DEVICE',
    'E-ZIP',
    'S-DATE',
    'E-ORGANIZATION',
    'S-PHONE',
    'S-STATE',
    'B-PROFESSION',
    'I-COUNTRY',
    'B-COUNTRY',
    'E-EMAIL',
    'I-DEVICE',
    'B-FAX',
    PAD,
    CLS,
    SEP,
    WORDPIECE
]

DEID_LABELS = {
    PAD:               0,
    'S-ORGANIZATION':  1,
    'O':               2,
    'S-PATIENT':       3,
    'B-STATE':         4,
    'B-MEDICALRECORD': 5,
    'S-MEDICALRECORD': 6,
    'B-DOCTOR':        7,
    'B-HOSPITAL':      8,
    'S-DOCTOR':        9,
    'B-PATIENT':       10,
    'S-CITY':          11,
    'B-EMAIL':         12,
    'S-COUNTRY':       13,
    'B-CITY':          14,
    'B-STREET':        15,
    'S-HOSPITAL':      16,
    'S-PROFESSION':    17,
    'S-AGE':           18,
    'B-DATE':          19,
    'B-IDNUM':         20,
    'S-USERNAME':      21,
    'B-PHONE':         22,
    'S-IDNUM':         23,
    'B-ORGANIZATION':  24,
    'S-ZIP':           25,
    'S-DATE':          26,
    'S-PHONE':         27,
    'S-STATE':         28,
    'B-PROFESSION':    29,
    'B-COUNTRY':       30,
    'B-FAX':           31,
    WORDPIECE:         32
}

COHORT_LABEL_CONSTANTS = {
    'U': 0,
    'Q': 1,
    'N': 2,
    'Y': 3,
}

COHORT_DISEASE_LIST = [
    'Obesity',
    'Diabetes',
    'Hypercholesterolemia',
    'Hypertriglyceridemia',
    'Hypertension',
    'CAD',
    'CHF',
    'PVD',
    'Venous Insufficiency',
    'OA',
    'OSA',
    'Asthma',
    'GERD',
    'Gallstones',
    'Depression',
    'Gout'
]

COHORT_DISEASE_CONSTANTS = {
    'Obesity': 0,
    'Diabetes': 1,
    'Hypercholesterolemia': 2,
    'Hypertriglyceridemia': 3,
    'Hypertension': 4,
    'CAD': 5,
    'CHF': 6,
    'PVD': 7,
    'Venous Insufficiency': 8,
    'OA': 9,
    'OSA': 10,
    'Asthma': 11,
    'GERD': 12,
    'Gallstones': 13,
    'Depression': 14,
    'Gout': 15
}

MAX_COHORT_NUM_SENTS = 256  # number of sentences in chart
